[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }

# decorations = "Full" | "None" | "Transparent" | "Buttonless"
#     Window decorations.
#     Full
#         Borders and title bar.
#     None
#         Neither borders nor title bar.
#     Transparent (macOS only)
#         Title bar, transparent background and title bar buttons.
#     Buttonless (macOS only)
#         Title bar, transparent background and no title bar buttons.
#     Default: "Full"
decorations = "Buttonless"

# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
#     Startup mode (changes require restart)
#     Windowed
#         Regular window.
#     Maximized
#         The window will be maximized on startup.
#     Fullscreen
#         The window will be fullscreened on startup.
#     SimpleFullscreen (macOS only)
#         Same as Fullscreen, but you can stack windows on top.
#     Default: "Windowed"
startup_mode = "Maximized"
